#! /bin/bash
# This script is created by Mukaram Pasha, Security analyst currently working at ATOS.
echo ""
 figlet -f small "Reverse NS lookup Script"
echo ""
echo ""
echo " Created by -"
figlet -f small "Mukaram Pasha"
echo ""
echo "Linkedin - https://www.linkedin.com/in/mukaram-pasha-67708315b"
echo "Script running time"
date
echo ""
echo ""
echo "Prerequsite - Add the IPs in a file with the name data.csv"
echo ""

while IFS="," read -r IP_ADDRESS

do
TEMPNUM="$IP_ADDRESS"
case "$TEMPNUM" in

""*"")

 dig -x $IP_ADDRESS +short > temp.txt

while read line; do echo Domain of the IP address $IP_ADDRESS is $line; done < temp.txt

   ;;
 esac

done < <(tail -n +2 data.csv)

